### ISSUE TITLE
[BUG] Commiting in GitHub Desktop causes node error

### ISSUE THREAD

**Issue by amuck-gorilla** [pagefaultgames/pokerogue#2775]
### Resolution
As of 7/5/2024, committing using GitHub Desktop on Windows 11 is not supported, due to an error with the pre-commit hook, (`lefthook.yml`), throwing an error.

### Original report 
**Describe the bug**

When I try to commit in GitHub Desktop, I get a popup with the following error.
`/usr/bin/env: ‘node’: No such file or directory`

**To Reproduce**

1. Open your fork of Pokérogue
2. Make a change to a file (I ran `npm update`, which automatically changed `package-lock.json`)
3. Open GitHub Desktop
4. Select your repository
5. Enter in a message and description for your commit
6. Press "Commit to **main**"
7. See error

**Expected behavior**

Commit goes through

**Screenshots / Videos**

<img width="720" alt="Screenshot 2024-07-03 115648" src="https://github.com/pagefaultgames/pokerogue/assets/83174140/7f04a9b8-0f3e-4440-9641-347cd5a74934">

**Device**

I am on an x64-based PC running Microsoft Windows 11 Home, Version 10.0.22631 Build 22631

**Additional context**

I have checked and I do have Node.js installed. I suspect that the root cause may be `lefthook.yml` running in some strange GitHub context without Node.js available, ***OR*** the context is falling victim to the legacy Node problem, [linked here on StackOverflow.](https://stackoverflow.com/a/27416100)

**Comment by flx-sta** [comment]
That’s because of `left-hook` running a es-lint check. It probably is missing the node environment

**Comment by amuck-gorilla** [comment]
> That’s because of `left-hook` running a es-lint check. It probably is missing the node environment

That's what I thought. Is there any way to fix that? My only idea was to install node in git bash, but I couldn't figure out how to do that, or if it's even possible.

**Comment by flx-sta** [comment]
> > That’s because of `left-hook` running a es-lint check. It probably is missing the node environment
> 
> That's what I thought. Is there any way to fix that? My only idea was to install node in git bash, but I couldn't figure out how to do that, or if it's even possible.

Back then I fixed it by restarting my system

**Comment by amuck-gorilla** [comment]
> Back then I fixed it by restarting my system

Well, I just tried that and it didn't fix the problem. Good suggestion though.

**Comment by flx-sta** [comment]
technically you could bypass the hook by using 
`git push origin <branch> --no-verify`
Idk if left-hook is made to be able to use in gh-desktop

**Comment by amuck-gorilla** [comment]
Wait, [npx is deprecated](https://www.npmjs.com/package/npx). That might be the problem. I'm going to try to see if changing it to npm run fixes the problem.

**Comment by flx-sta** [comment]
> Wait, [npx is deprecated](https://www.npmjs.com/package/npx). That might be the problem. I'm going to try to see if changing it to npm run fixes the problem.

Just to clear this up for others:
`npx` as a standalone package is deprecated as it is part of the default npm environment nowadays.

btw I recommend you to install [Volta.sh](https://volta.sh/). It’s a node version manager that handles a lot of nuisances for you automatically.

**Comment by amuck-gorilla** [comment]
> btw I recommend you to install [Volta.sh](https://volta.sh/). It’s a node version manager that handles a lot of nuisances for you automatically.

I tried switching to `npm run`, I tried installing Volta.sh, and I even restarted my system, and none of those fixed the problem. I confirmed that it is **just** Github Desktop that's broken, but it still doesn't work. Any more suggestions?

**Comment by flx-sta** [comment]
> > btw I recommend you to install [Volta.sh](https://volta.sh/). It’s a node version manager that handles a lot of nuisances for you automatically.
> 
> I tried switching to `npm run`, I tried installing Volta.sh, and I even restarted my system, and none of those fixed the problem. I confirmed that it is **just** Github Desktop that's broken, but it still doesn't work. Any more suggestions?

not using github desktop 🥶

**Comment by amuck-gorilla** [comment]
> not using github desktop 🥶

That's what I thought. Disappointing.

**Comment by amuck-gorilla** [comment]
For anyone having this problem in the future who didn't read the edited report, as of 7/5/2024, committing using GitHub Desktop on Windows 11 is not supported, because the pre-commit hook throws an error.
